INSERT INTO FILMS (NAME, DESCRIPTION)
VALUES ('Terminator', 'descFi');

INSERT INTO FILMS (NAME, DESCRIPTION)
VALUES ('Aline', 'descFi');

INSERT INTO FILMS (NAME, DESCRIPTION)
VALUES ('What the it', 'descFi');

UPDATE FILMS
SET NAME         = 'Terminal',
    DESCRIPTION  = 'hi',
    RELEASE_DATE = CURRENT_DATE,
    DURATION     = 123
WHERE ID = 3;

-------------------------
INSERT INTO USERS (EMAIL, LOGIN)
VALUES ('zre@mail.ru', 'ArtQ');

INSERT INTO USERS (EMAIL, LOGIN)
VALUES ('chi@mail.ru', 'Anna');

INSERT INTO USERS (EMAIL, LOGIN)
VALUES ('fjq@mail.ru', 'Kir');

---------------------------
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
VALUES (1, 2, 'PENDING');

INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
VALUES (1, 3, 'PENDING');

INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
VALUES (2, 3, 'PENDING');

UPDATE FRIENDS
SET STATUS = 'ACCEPTED'
WHERE USER_ID = 1
  AND FRIEND_ID = 3;

UPDATE FRIENDS
SET STATUS = 'ACCEPTED'
WHERE USER_ID = 2
  AND FRIEND_ID = 3;

UPDATE FRIENDS
SET STATUS = 'REJECTED'
WHERE USER_ID = 1
  AND FRIEND_ID = 2;

SELECT *
FROM FRIENDS
WHERE (USER_ID = 3 or FRIEND_ID = 3)
  AND STATUS = 'ACCEPTED';

SELECT *
FROM FRIENDS
WHERE (USER_ID = 1 AND FRIEND_ID = 4)
   OR (USER_ID = 4 AND FRIEND_ID = 1);


SELECT f1.FRIEND_ID
FROM friends f1
         JOIN friends f2 ON f1.friend_id = f2.friend_id
WHERE f1.user_id = 1
  AND f2.user_id = 2
  AND f1.status = 'ACCEPTED'
  AND f2.status = 'ACCEPTED'