INSERT INTO GENRE (TITLE)
SELECT 'COMEDY'
WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE TITLE = 'COMEDY');
INSERT INTO GENRE (TITLE)
SELECT 'DRAMA'
WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE TITLE = 'DRAMA');
INSERT INTO GENRE (TITLE)
SELECT 'CARTOON'
WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE TITLE = 'CARTOON');
INSERT INTO GENRE (TITLE)
SELECT 'THRILLER'
WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE TITLE = 'THRILLER');
INSERT INTO GENRE (TITLE)
SELECT 'DOCUMENTARY'
WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE TITLE = 'DOCUMENTARY');
INSERT INTO GENRE (TITLE)
SELECT 'ACTION'
WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE TITLE = 'ACTION');

-------------------------------------

INSERT INTO MPA (TITLE)
SELECT 'G'
WHERE NOT EXISTS (SELECT 1 FROM MPA WHERE TITLE = 'G');
INSERT INTO MPA (TITLE)
SELECT 'PG'
WHERE NOT EXISTS (SELECT 1 FROM MPA WHERE TITLE = 'PG');
INSERT INTO MPA (TITLE)
SELECT 'PG_13'
WHERE NOT EXISTS (SELECT 1 FROM MPA WHERE TITLE = 'PG_13');
INSERT INTO MPA (TITLE)
SELECT 'R'
WHERE NOT EXISTS (SELECT 1 FROM MPA WHERE TITLE = 'R');
INSERT INTO MPA (TITLE)
SELECT 'NC_17'
WHERE NOT EXISTS (SELECT 1 FROM MPA WHERE TITLE = 'NC_17');

------------------------------------

-- INSERT INTO FILMS (NAME, DESCRIPTION)
-- VALUES ('Terminator', 'descFi');
--
-- INSERT INTO FILMS (NAME, DESCRIPTION)
-- VALUES ('Aline', 'descFi');
--
-- INSERT INTO FILMS (NAME, DESCRIPTION)
-- VALUES ('What the it', 'descFi');

-------------------------

-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('zre@mail.ru', 'ArtQ');
--
-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('chi@mail.ru', 'Anna');
--
-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('fjq@mail.ru', 'Kir');
--
-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('fAjq@mail.ru', 'Kir');
--
-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('fFAjq@mail.ru', 'Kir');

---------------------------

-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 2, 'PENDING');
--
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 3, 'PENDING');
--
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (2, 3, 'PENDING');

-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 2, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 3, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 4, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (2, 3, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (2, 5, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (3, 5, 'ACCEPTED');


-- SELECT DISTINCT USER_ID
-- FROM FRIENDS
-- WHERE STATUS = 'ACCEPTED'
--   AND FRIEND_ID IN (1, 2)
--   AND USER_ID NOT IN (1, 2)
-- UNION
-- SELECT FRIEND_ID AS ID
-- FROM FRIENDS
-- WHERE STATUS = 'ACCEPTED'
--   AND USER_ID IN (1, 2)
--   AND FRIEND_ID NOT IN (1, 2);
--
--
-- SELECT USER_ID ID
-- FROM FRIENDS
-- WHERE FRIEND_ID = 2
--   AND STATUS = 'ACCEPTED'
-- UNION ALL
-- SELECT FRIEND_ID ID
-- FROM FRIENDS
-- WHERE USER_ID = 2
--   AND STATUS = 'ACCEPTED';
