INSERT INTO GENRE (TITLE)
VALUES ('COMEDY'),
       ('DRAMA'),
       ('CARTOON'),
       ('THRILLER'),
       ('DOCUMENTARY'),
       ('ACTION');

-------------------------------------

INSERT INTO MPA (TITLE)
VALUES ('G'),
       ('PG'),
       ('PG_13'),
       ('R'),
       ('NC_17');

------------------------------------

-- INSERT INTO FILMS (NAME, DESCRIPTION)
-- VALUES ('Terminator', 'descFi');
--
-- INSERT INTO FILMS (NAME, DESCRIPTION)
-- VALUES ('Aline', 'descFi');
--
-- INSERT INTO FILMS (NAME, DESCRIPTION)
-- VALUES ('What the it', 'descFi');

-------------------------

-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('zre@mail.ru', 'ArtQ');
--
-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('chi@mail.ru', 'Anna');
--
-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('fjq@mail.ru', 'Kir');
--
-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('fAjq@mail.ru', 'Kir');
--
-- INSERT INTO USERS (EMAIL, LOGIN)
-- VALUES ('fFAjq@mail.ru', 'Kir');

---------------------------

-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 2, 'PENDING');
--
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 3, 'PENDING');
--
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (2, 3, 'PENDING');

-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 2, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 3, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (1, 4, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (2, 3, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (2, 5, 'ACCEPTED');
-- INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS)
-- VALUES (3, 5, 'ACCEPTED');


-- SELECT DISTINCT USER_ID
-- FROM FRIENDS
-- WHERE STATUS = 'ACCEPTED'
--   AND FRIEND_ID IN (1, 2)
--   AND USER_ID NOT IN (1, 2)
-- UNION
-- SELECT FRIEND_ID AS ID
-- FROM FRIENDS
-- WHERE STATUS = 'ACCEPTED'
--   AND USER_ID IN (1, 2)
--   AND FRIEND_ID NOT IN (1, 2);
--
--
-- SELECT USER_ID ID
-- FROM FRIENDS
-- WHERE FRIEND_ID = 2
--   AND STATUS = 'ACCEPTED'
-- UNION ALL
-- SELECT FRIEND_ID ID
-- FROM FRIENDS
-- WHERE USER_ID = 2
--   AND STATUS = 'ACCEPTED';


